server:
  port: 8222
spring:
  application:
    name: show-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myxue?characterEncoding=utf-8
   #注册上去的ip
  cloud:
    inetutils:
      default-ip-address: 172.18.0.5
eureka:
  instance:
    hostname: localhost
    #可以以ip形式访问
    prefer-ip-address: true
    instance-id: ${spring.cloud.inetutils.default-ip-address}:${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekas:8761/eureka
#配置mybatis-plus打印sql语句于控制台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名转换
    map-underscore-to-camel-case: true
