server:
  port: 5555
spring:
  application:
    name: zuul-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myxue?characterEncoding=utf-8
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  prefix: /api
  #转发服务
  routes:
    other:
      path: /other-server/**
      serviceId: other-server
#配置mybatis-plus打印sql语句于控制台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名转换
    map-underscore-to-camel-case: true
